### ISSUE TITLE
Accessor interface always null when call it in Data Layer Project 

### ISSUE THREAD

**Issue by ngockhoa8989** [usausa/Smart-Net-Data-Accessor#1]
**Error**: 
```
Smart.Data.Accessor.AccessorRuntimeException: Accessor implement not exist. type=[nCanary.DAL.Accessor.IAccountAccessor]
   at Smart.Data.Accessor.DataAccessorFactory.Create(Type type)
   at Smart.Data.Accessor.DataAccessorFactory.Create[T]()
   at Smart.Data.Accessor.Extensions.DependencyInjection.AccessorResolver`1..ctor(DataAccessorFactory dataAccessorFactory)
```
I didn't implement 2waySQL directly on Web API or Web App Project. I structured project 3 layer: and implement 2waySQL in Data Layer prorject. But when call Accessor, it always return null and not connect to sql file 

Please help me to solve this issue 

Many thanks,

**Comment by usausa** [comment]
Does Xxx.Accessor.DataAccessor.dll exist with Xxx.Accessor.dll in bin directory?
Xxx.Accessor.DataAccessor.dll is an implementation assembly created based on the interface.
Usually, it is copied to bin directory with Xxx.Accessor.dll at build time.

I made layered sample, please check the difference.
[Example.zip](https://github.com/usausa/Smart-Net-Data-Accessor/files/4343608/Example.zip)

**Comment by chanh2505** [comment]
Thanks usausa,

Your example's very clear and easy to understand. I resolved my issue. Thanks again.

**Comment by ngockhoa8989** [comment]
Thanks so much usausa, 

I resolved my issue. Love your library.
