### ISSUE TITLE
How to use "IN" clause with Smart?

### ISSUE THREAD

**Issue by nShieldSolo** [usausa/Smart-Net-Data-Accessor#5]
Dear Sir, 

   I want execute the query with IN clause like this:
 `SELECT * FROM nca_email_log WHERE  LOWER(status_send_mail) IN LOWER(/* @ Status */''))`
 Please guide me how to implement it.

May thanks,

**Comment by usausa** [comment]
Sorry, the only process supported is simple array/list expansion like `IN (@p1, @p2 , ...)`.
It does not support parsing to expand as in `IN (LOWER(@p1), LOWER(@p2), ...)`.
You can write a loop in the SQL in a code comment, but it is recommended to use a `ToLower()` "Status" element on the application side as an argument and the SQL should be `IN /*@ LowerStatus */('')`.
